version: '3'
  
services:
  zookeeper-conf:
    image: confluentinc/cp-zookeeper:7.2.6
    container_name: zookeeper-conf
    ports:
      - "22181:2181"
    volumes:
      - zookeeper-data:/var/lib/zookeeper/data
      - zookeeper-log:/var/lib/zookeeper/log
    environment:
      ZOOKEEPER_SERVER_ID: 1
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    restart: always 
  
  kafka-conf:
    image: confluentinc/cp-kafka:7.2.6
    container_name: kafka-conf
    ports:
      - "19092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
      KAFKA_ZOOKEEPER_CONNECT: zookeeper-conf:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka-conf:9092,PLAINTEXT_HOST://localhost:19092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      ALLOW_PLAINTEXT_LISTENER: "yes"
    volumes:
      - kafka-data:/var/lib/kafka/data
    depends_on:
      - zookeeper-conf
    restart: always

  kafdrop:
    image: obsidiandynamics/kafdrop:latest
    ports:
      - "9000:9000"
    environment: 
      KAFKA_BROKERCONNECT: "PLAINTEXT://kafka-conf:9092"
    depends_on: 
      - "kafka-conf"

volumes:
  zookeeper-data:
    driver: local
  zookeeper-log:
    driver: local
  kafka-data:
    driver: local

