spring:
  application:
    name: product-service
  data:
    mongodb:
      uri: mongodb://mongodb:27017/product-service

eureka:
  client:
    serviceUrl:
      defaultZone: http://discovery-server:8761/eureka

server:
  port: 0
