version: '3.7'
services:
  grafana:
    image: grafana/grafana:5.4.3
    hostname: grafana
    ports:
      - 3000:3000
    volumes:
      - ./grafana:/var/lib/grafana
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
   # networks:
    #  - ${GLOBAL_NETWORK:-grafana}
  prometheus:
    image: prom/prometheus:v2.19.2
    hostname: prometheus
    ports:
      - 9090:9090
    volumes:
      - ./config/prometheus.yml:/etc/prometheus/prometheus.yml
      - ./prometheus:/prometheus
    environment:
      - log_level=debug
    #networks:
     # - ${GLOBAL_NETWORK:-prometheus}

