spring:
      application:
          name: ProductService
      data:
          mongodb:
              uri: mongodb://localhost:27017/ProductService
eureka:
  client:
    serviceUrl:
      defaultZone : http://localhost:8761/eureka
server:
    port : 0